### Logistics Regression Implementation

In [56]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [57]:
from sklearn.datasets import make_classification

In [58]:
## create the dataset
X , y = make_classification(n_classes=2, n_samples=1000, n_features=10, random_state=43)

In [59]:
pd.DataFrame(X)

0         1         2         3         4         5         6  \
0   -1.129510  0.313954  0.226078 -0.602014  0.364379  1.495656  0.289715   
1    0.764545  1.593521 -0.486190 -0.331393 -0.361425 -0.561112  0.680599   
2   -0.906067  1.432046 -2.108286  0.157747  1.040965 -2.625549  0.481348   
3    1.038484 -0.032419 -2.774775 -0.324353 -0.859559 -0.813757 -0.812063   
4   -2.299785  3.140142 -0.865061 -1.259801  1.931235  0.309015  1.422955   
..        ...       ...       ...       ...       ...       ...       ...   
995  0.660264 -0.708928  1.565611 -0.314670 -0.721552 -1.070590 -0.703302   
996 -2.562809  0.749578 -1.422529  1.584695  0.041969 -1.039793 -0.993587   
997 -0.677147 -1.655376  0.519085  1.278970 -1.559456  0.920620 -0.904188   
998 -0.244108  0.874514 -0.721472  1.424230 -0.448167 -0.050433 -0.510640   
999  1.023990 -0.418205 -0.453333  1.253078 -1.828315  0.898468 -2.646676   

            7         8         9  
0    1.295559 -0.949006  0.947923  
1   -0.723086  0.492374 -0.036138  
2   -0.501548  0.646272  1.066529  
3   -1.402447  0.917563  0.687776  
4    2.225362 -1.322112 -1.902240  
..        ...       ...       ...  
995 -1.413346  0.958831 -0.210503  
996 -0.589209  0.480600 -0.114143  
997 -1.084067  0.498088  0.841691  
998 -0.503459  0.296456  1.509820  
999 -1.381160  0.671991  0.780982  

[1000 rows x 10 columns]

In [60]:
y

array([1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1,
       1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1,
       1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1,
       1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1,
       1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1,

In [61]:
from sklearn.model_selection import train_test_split
X_train , X_test, y_train , y_test = train_test_split(X,y,test_size=0.30, random_state=42)

In [62]:
X_train.shape , X_test.shape , y_train.shape , y_test.shape

((700, 10), (300, 10), (700,), (300,))

In [63]:
# Model Training
from sklearn.linear_model import LogisticRegression
log = LogisticRegression()

In [64]:
log.fit(X_train, y_train)

LogisticRegression()

In [ ]:
y_pred = log.predict(X_test)

In [66]:
y_pred

array([1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0,
       1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1,
       1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0])

In [67]:
### Performance Metrics
from sklearn.metrics import accuracy_score, confusion_matrix , classification_report

In [68]:
score = accuracy_score(y_test, y_pred)
score

0.93

In [69]:
cm = confusion_matrix(y_test, y_pred)
cm

array([[138,  15],
       [  6, 141]], dtype=int64)

In [70]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.96      0.90      0.93       153
           1       0.90      0.96      0.93       147

    accuracy                           0.93       300
   macro avg       0.93      0.93      0.93       300
weighted avg       0.93      0.93      0.93       300



### Hyper Parameter Tuning and Cross Validation

In [71]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()

In [72]:
penalty = ['l1', 'l2', 'elasticnet']
c_values = [100,10,1.0,0.1,0.01]
solver = ['lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga']

In [73]:
params = dict(penalty = penalty , C = c_values , solver=solver)

In [74]:
params

{'penalty': ['l1', 'l2', 'elasticnet'],
 'C': [100, 10, 1.0, 0.1, 0.01],
 'solver': ['lbfgs',
  'liblinear',
  'newton-cg',
  'newton-cholesky',
  'sag',
  'saga']}

In [75]:
from sklearn.model_selection import StratifiedKFold
cv = StratifiedKFold()

In [76]:
from sklearn.model_selection import GridSearchCV
grid = GridSearchCV(estimator= model,param_grid= params ,scoring= 'accuracy' , cv=cv)

In [77]:
grid

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(),
             param_grid={'C': [100, 10, 1.0, 0.1, 0.01],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['lbfgs', 'liblinear', 'newton-cg',
                                    'newton-cholesky', 'sag', 'saga']},
             scoring='accuracy')

In [78]:
grid.fit(X_train , y_train)

c:\ProgramData\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\ProgramData\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\ProgramData\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\ProgramData\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\ProgramData\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\ProgramData\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:349: ConvergenceWarning: The max_iter 

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(),
             param_grid={'C': [100, 10, 1.0, 0.1, 0.01],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['lbfgs', 'liblinear', 'newton-cg',
                                    'newton-cholesky', 'sag', 'saga']},
             scoring='accuracy')

In [79]:
grid.best_params_

{'C': 0.1, 'penalty': 'l2', 'solver': 'lbfgs'}

In [80]:
grid.best_score_

0.9328571428571429

In [82]:
y_pred = grid.predict(X_test)

In [83]:
from sklearn.metrics import accuracy_score , confusion_matrix , classification_report
score = accuracy_score(y_test , y_pred)
score

0.9266666666666666

### Randomized Search CV

In [84]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()

In [85]:
from sklearn.model_selection import RandomizedSearchCV
random = RandomizedSearchCV(estimator=model, param_distributions=params, cv = cv ,scoring='accuracy' )

In [86]:
random.fit(X_train , y_train)

c:\ProgramData\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:540: FitFailedWarning: 
20 fits failed out of a total of 50.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "c:\ProgramData\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "c:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\ProgramData\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py", line 1194, in fit
    solver = _c

RandomizedSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
                   estimator=LogisticRegression(),
                   param_distributions={'C': [100, 10, 1.0, 0.1, 0.01],
                                        'penalty': ['l1', 'l2', 'elasticnet'],
                                        'solver': ['lbfgs', 'liblinear',
                                                   'newton-cg',
                                                   'newton-cholesky', 'sag',
                                                   'saga']},
                   scoring='accuracy')

In [93]:
random.best_params_

{'solver': 'sag', 'penalty': 'l2', 'C': 0.1}

In [87]:
random.best_score_

0.9328571428571429

In [91]:
y_pred = random.predict(X_test)

In [92]:
from sklearn.metrics import accuracy_score , confusion_matrix , classification_report
score = accuracy_score(y_test , y_pred)
score

0.9266666666666666